name: carpenter
description: A semantic and adaptive UI platform for Flutter applications across desktop, web, and mobile.
version: 0.1.4
repository: https://github.com/Albizia-Dev/carpenter
issue_tracker: https://github.com/Albizia-Dev/carpenter/issues
topics:
  - flutter
  - design-system
  - ui
  - components
  - adaptive-ui

environment:
  sdk: ">=3.12.2 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.1
  carpenter_mordant: ^0.4.1
  carpenter_units: ^0.3.0
  flutter_svg: ^2.3.0
  yx_navigation: ^1.0.0

dev_dependencies:
  build_runner: 2.7.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/icons/gravity/
