// GENERATED by dsktp/tool/work_items/generate_fixtures.py. Do not edit.
import 'package:carpenter/carpenter.dart';

const workInboxScenarioEntries = <String, String>{
  "develop": "zodo:1:next",
  "accept": "rsp:2:next",
  "deadline": "rsp:3:next",
  "test": "zodo:4:next",
  "execute": "rsp:5:next",
};
const workInboxKinds = <String, String>{
  "zodo:1:next": "zodo",
  "rsp:2:next": "rsp",
  "rsp:3:next": "rsp",
  "zodo:4:next": "zodo",
  "rsp:5:next": "rsp",
};
const workInboxItems = <CarpenterWorkInboxItem>[
  CarpenterWorkInboxItem(
    id: "rsp:2:next",
    reference: "РСП №501",
    title: "Согласовать счёт на поставку материалов",
    description:
        "Поставщик прислал счёт и спецификацию. Проверьте состав поставки перед подтверждением результата.",
    status: "Ожидает подтверждения",
    reason: "Исполнитель представил результат",
    nextAction: "Проверить и подтвердить результат",
    creator: "Анна Смирнова",
    assignee: "Алексей Орлов",
    deadline: "11.09.2026 · 10:00 UTC",
  ),
  CarpenterWorkInboxItem(
    id: "rsp:3:next",
    reference: "РСП №502",
    title: "Уточнить срок подготовки спецификации",
    description:
        "Нужен ответ поставщика по комплектующим. Исполнитель предлагает закончить подготовку во вторник.",
    status: "Предложен новый срок",
    reason: "Исполнитель запросил перенос",
    nextAction: "Рассмотреть предложенный срок",
    creator: "Анна Смирнова",
    assignee: "Алексей Орлов",
    deadline: "12.09.2026 · 10:00 UTC",
    requestedDeadline: "15.09.2026 · 10:00 UTC",
  ),
  CarpenterWorkInboxItem(
    id: "rsp:5:next",
    reference: "РСП №503",
    title:
        "Подготовить документы для реконструкции инженерных сетей квартала «Северный парк»",
    description:
        "Собрать исходные материалы и передать результат создателю поручения.",
    status: "В работе",
    reason: "Поручение назначено вам",
    nextAction: "Подготовить результат",
    creator: "Анна Смирнова",
    assignee: "Алексей Орлов",
    deadline: "16.09.2026 · 10:00 UTC",
  ),
  CarpenterWorkInboxItem(
    id: "zodo:1:next",
    reference: "ЗОДО №104",
    title: "Восстановить черновик после конфликта сохранения",
    description:
        "Пользователь должен сохранить свой текст при обновлении карточки другим сотрудником.",
    status: "В работе",
    reason: "Вы ведёте эту задачу",
    nextAction: "Продолжить работу",
    creator: "Анна Смирнова",
    assignee: "Алексей Орлов",
  ),
  CarpenterWorkInboxItem(
    id: "zodo:4:next",
    reference: "ЗОДО №108",
    title: "Проверить поиск в длинном списке проектов",
    description:
        "Выбранные проекты должны оставаться видны при изменении поискового запроса.",
    status: "Тестирование",
    reason: "Вы назначены тестировщиком",
    nextAction: "Проверить результат",
    creator: "Анна Смирнова",
    assignee: "Алексей Орлов",
  ),
];
