// GENERATED by dsktp/tool/work_items/generate_fixtures.py. Do not edit.
const rspAcceptanceReference = "РСП №501";
const rspAcceptanceExecutor = "Алексей Орлов";
const rspAcceptanceResultText =
    "Счёт и спецификация подготовлены. Позиции сверены с заявкой; требуется подтверждение создателя поручения.";
